package org.newdeal.core.system.request;

import org.newdeal.core.bean.Referenceable;

import java.time.Instant;
import java.util.Optional;

/**
 * @author Frederick Vanderbeke
 * @since 31/07/2015.
 */
public interface DispatchedRequest extends SubmittedRequest {
    /**
     * Can be used to track the sequence of entries in the station.
     *
     * @return the admission ticket. This ticket is created by the station when the request enters in it.
     */
    long getTicket();

    /**
     * Can be used to track the allocation sequence performed by the station.
     *
     * @return the allocation token. This token is generated by the station when the request is correctly allocated to
     *         a processor.
     */
    default Optional<Long> getAllocationToken() {
        return Optional.empty();
    }

    Instant getDispatchDate();

    Referenceable getProcessorRef();
}
